Repository DLR-SC/ESID, pull requests merged in 2023-01, with the labels that each got.

#194 :wrench: Slight refactoring to improve page load times.
  frontend/.prettierrc
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/assets/third-party-attributions.json
  frontend/src/components/IconBar.tsx
  frontend/src/components/ScenarioCard.tsx
  frontend/src/components/Sidebar/DistrictMap.tsx
  frontend/src/main.tsx
Labels: class:enhancement, type:web-frontend

#198 :tada: Add Issue Forms
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/FEEDBACK-REPORT.yml
Labels: class:enhancement

#195 :truck: Improve mui imports to reduce bundle size.
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/IconBar.tsx
  frontend/src/components/MainContent.tsx
  frontend/src/components/Scenario.tsx
  frontend/src/components/ScenarioCard.tsx
  frontend/src/components/Sidebar/DistrictMap.tsx
  frontend/src/components/Sidebar/HeatLegend.tsx
  frontend/src/components/Sidebar/HeatLegendEdit.tsx
  frontend/src/components/Sidebar/SearchBar.tsx
  frontend/src/components/Sidebar/SidebarDetails.tsx
  frontend/src/components/Sidebar/SidebarTabs.tsx
  frontend/src/components/Sidebar/index.tsx
  frontend/src/components/SimulationChart.tsx
  frontend/src/components/TopBar/ApplicationMenu.tsx
  frontend/src/components/TopBar/PopUps/AccessibilityDialog.tsx
  frontend/src/components/TopBar/PopUps/AttributionDialog.tsx
  frontend/src/components/TopBar/PopUps/ImprintDialog.tsx
  frontend/src/components/TopBar/PopUps/PrivacyPolicyDialog.tsx
  frontend/src/components/TopBar/index.tsx
  frontend/src/components/shared/LoadingContainer.tsx
  frontend/src/components/shared/LoadingOverlay.tsx
Labels: class:refactoring
